services:
  - type: web
    name: tour-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn tours_app:app
    rootDir: backend/tour_api

  - type: web
    name: hotel-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn hotel_app:app
    rootDir: backend/hotel_api

  - type: web
    name: car-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn car_app:app
    rootDir: backend/car_api
